// LOAD USER
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

// LOG IN
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

// LOGOUT
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

// REGISTER USER
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// REGISTER USER
export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

// REDIRECT URL
export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';

// CHECK TOKEN
export const CHECK_TOKEN = 'CHECK_TOKEN';

// CONTACT
export const CONTACT_REQUEST = 'CONTACT_REQUEST';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAILURE = 'CONTACT_FAILURE';

export const CONTACT_TEAM_REQUEST = 'CONTACT_TEAM_REQUEST';
export const CONTACT_TEAM_SUCCESS = 'CONTACT_TEAM_SUCCESS';
export const CONTACT_TEAM_FAILURE = 'CONTACT_TEAM_FAILURE';

export const CONTACT_TEAM_RESET = 'CONTACT_TEAM_RESET';

// LEAGUE DETAILS
export const LEAGUE_PROFILE_REQUEST = 'LEAGUE_PROFILE_REQUEST';
export const LEAGUE_PROFILE_SUCCESS = 'LEAGUE_PROFILE_SUCCESS';
export const LEAGUE_PROFILE_FAILURE = 'LEAGUE_PROFILE_FAILURE';

// TEAM PROFILE
export const TEAM_PROFILE_REQUEST = 'TEAM_PROFILE_REQUEST';
export const TEAM_PROFILE_SUCCESS = 'TEAM_PROFILE_SUCCESS';
export const TEAM_PROFILE_FAILURE = 'TEAM_PROFILE_FAILURE';

// ATHLETE PROFILE
export const ATHLETE_PROFILE_REQUEST = 'ATHLETE_PROFILE_REQUEST';
export const ATHLETE_PROFILE_SUCCESS = 'ATHLETE_PROFILE_SUCCESS';
export const ATHLETE_PROFILE_FAILURE = 'ATHLETE_PROFILE_FAILURE';

// EXPLORE
export const EXPLORE_LEAGUES_REQUEST = 'EXPLORE_LEAGUES_REQUEST';
export const EXPLORE_LEAGUES_SUCCESS = 'EXPLORE_LEAGUES_SUCCESS';
export const EXPLORE_LEAGUES_FAILURE = 'EXPLORE_LEAGUES_FAILURE';

export const EXPLORE_TEAMS_REQUEST = 'EXPLORE_TEAMS_REQUEST';
export const EXPLORE_TEAMS_SUCCESS = 'EXPLORE_TEAMS_SUCCESS';
export const EXPLORE_TEAMS_FAILURE = 'EXPLORE_TEAMS_FAILURE';

export const EXPLORE_ATHLETES_REQUEST = 'EXPLORE_ATHLETES_REQUEST';
export const EXPLORE_ATHLETES_SUCCESS = 'EXPLORE_ATHLETES_SUCCESS';
export const EXPLORE_ATHLETES_FAILURE = 'EXPLORE_ATHLETES_FAILURE';

// TEAM REQUEST POSITION
export const TEAM_REQUEST_POSITION_REQUEST = 'TEAM_REQUEST_POSITION_REQUEST';
export const TEAM_REQUEST_POSITION_SUCCESS = 'TEAM_REQUEST_POSITION_SUCCESS';
export const TEAM_REQUEST_POSITION_FAILURE = 'TEAM_REQUEST_POSITION_FAILURE';

// ON BOARDING
export const ON_BOARDING_REQUEST = 'ON_BOARDING_REQUEST';
export const ON_BOARDING_SUCCESS = 'ON_BOARDING_SUCCESS';
export const ON_BOARDING_FAILURE = 'ON_BOARDING_FAILURE';

// CREATE LEAGUE PROFILE
export const CREATE_LEAGUE_REQUEST = 'CREATE_LEAGUE_REQUEST';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const CREATE_LEAGUE_FAILURE = 'CREATE_LEAGUE_FAILURE';

// EDIT LEAGUE PROFILE
export const EDIT_LEAGUE_REQUEST = 'EDIT_LEAGUE_REQUEST';
export const EDIT_LEAGUE_SUCCESS = 'EDIT_LEAGUE_SUCCESS';
export const EDIT_LEAGUE_FAILURE = 'EDIT_LEAGUE_FAILURE';

// STATS PAGE / LOAD DIVISION
export const FETCH_STATS_REQUEST = 'FETCH_STATS_REQUEST';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE';

// LEAGUE OWNERS
export const LEAGUE_OWNERS_REQUEST = 'LEAGUE_OWNERS_REQUEST';
export const LEAGUE_OWNERS_SUCCESS = 'LEAGUE_OWNERS_SUCCESS';
export const LEAGUE_OWNERS_FAILURE = 'LEAGUE_OWNERS_FAILURE';

// STATSFORM
export const FETCH_MATCHGAMES_REQUEST = 'FETCH_MATCHGAMES_REQUEST';
export const FETCH_MATCHGAMES_SUCCESS = 'FETCH_MATCHGAMES_SUCCESS';
export const FETCH_MATCHGAMES_FAILURE = 'FETCH_MATCHGAMES_FAILURE';

// CREATE DIVISION
export const CREATE_DIVISION_REQUEST = 'CREATE_DIVISION_REQUEST';
export const CREATE_DIVISION_SUCCESS = 'CREATE_DIVISION_SUCCESS';
export const CREATE_DIVISION_FAILURE = 'CREATE_DIVISION_FAILURE';

// EDIT DIVISION
export const EDIT_DIVISION_REQUEST = 'EDIT_DIVISION_REQUEST';
export const EDIT_DIVISION_SUCCESS = 'EDIT_DIVISION_SUCCESS';
export const EDIT_DIVISION_FAILURE = 'EDIT_DIVISION_FAILURE';

// NOTIFICATIONS
export const FETCH_ATHLETE_NOTIFICATIONS_REQUEST = 'FETCH_ATHLETE_NOTIFICATIONS_REQUEST';
export const FETCH_ATHLETE_NOTIFICATIONS_SUCCESS = 'FETCH_ATHLETE_NOTIFICATIONS_SUCCESS';
export const FETCH_ATHLETE_NOTIFICATIONS_FAILURE = 'FETCH_ATHLETE_NOTIFICATIONS_FAILURE';

export const PUT_ATHLETE_NOTIFICATIONS_REQUEST = 'PUT_ATHLETE_NOTIFICATIONS_REQUEST';
export const PUT_ATHLETE_NOTIFICATIONS_SUCCESS = 'PUT_ATHLETE_NOTIFICATIONS_SUCCESS';
export const PUT_ATHLETE_NOTIFICATIONS_FAILURE = 'PUT_ATHLETE_NOTIFICATIONS_FAILURE';

export const UPDATE_NOTIFICATION_REQUEST = 'UPDATE_NOTIFICATION_REQUEST';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_FAILURE = 'UPDATE_NOTIFICATION_FAILURE';

export const FETCH_TEAMCAPTAIN_NOTIFICATIONS_REQUEST = 'FETCH_TEAMCAPTAIN_NOTIFICATIONS_REQUEST';
export const FETCH_TEAMCAPTAIN_NOTIFICATIONS_SUCCESS = 'FETCH_TEAMCAPTAIN_NOTIFICATIONS_SUCCESS';
export const FETCH_TEAMCAPTAIN_NOTIFICATIONS_FAILURE = 'FETCH_TEAMCAPTAIN_NOTIFICATIONS_FAILURE';

// TEAM MANAGE
export const FETCH_TEAM_MANAGE_DETAILS_REQUEST = 'FETCH_TEAM_MANAGE_DETAILS_REQUEST';
export const FETCH_TEAM_MANAGE_DETAILS_SUCCESS = 'FETCH_TEAM_MANAGE_DETAILS_SUCCESS';
export const FETCH_TEAM_MANAGE_DETAILS_FAILURE = 'FETCH_TEAM_MANAGE_DETAILS_FAILURE';

export const REMOVE_DIVISION_ATHLETE_REQUEST = 'REMOVE_DIVISION_ATHLETE_REQUEST';
export const REMOVE_DIVISION_ATHLETE_SUCCESS = 'REMOVE_DIVISION_ATHLETE_SUCCESS';
export const REMOVE_DIVISION_ATHLETE_FAILURE = 'REMOVE_DIVISION_ATHLETE_FAILURE';

export const INVITE_DIVISION_ATHLETE_REQUEST = 'INVITE_DIVISION_ATHLETE_REQUEST';
export const INVITE_DIVISION_ATHLETE_SUCCESS = 'INVITE_DIVISION_ATHLETE_SUCCESS';
export const INVITE_DIVISION_ATHLETE_FAILURE = 'INVITE_DIVISION_ATHLETE_FAILURE';

export const INVITE_NEW_DIVISION_ATHLETE_REQUEST = 'INVITE_NEW_DIVISION_ATHLETE_REQUEST';
export const INVITE_NEW_DIVISION_ATHLETE_SUCCESS = 'INVITE_NEW_DIVISION_ATHLETE_SUCCESS';
export const INVITE_NEW_DIVISION_ATHLETE_FAILURE = 'INVITE_NEW_DIVISION_ATHLETE_FAILURE';
export const INVITE_NEW_DIVISION_ATHLETE_RESET = 'INVITE_NEW_DIVISION_ATHLETE_RESET';

// PRIVATE SETTINGS
export const EDIT_PROFILE_URL_REQUEST = 'EDIT_PROFILE_URL_REQUEST';
export const EDIT_PROFILE_URL_SUCCESS = 'EDIT_PROFILE_URL_SUCCESS';
export const EDIT_PROFILE_URL_FAILURE = 'EDIT_PROFILE_URL_FAILURE';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const DEACTIVATE_ACCOUNT_REQUEST = 'DEACTIVATE_ACCOUNT_REQUEST';
export const DEACTIVATE_ACCOUNT_SUCCESS = 'DEACTIVATE_ACCOUNT_SUCCESS';
export const DEACTIVATE_ACCOUNT_FAILURE = 'DEACTIVATE_ACCOUNT_FAILURE';

// CREATE NEW TEAM
export const CREATE_NEW_TEAM_REQUEST = 'CREATE_NEW_TEAM_REQUEST';
export const CREATE_NEW_TEAM_SUCCESS = 'CREATE_NEW_TEAM_SUCCESS';
export const CREATE_NEW_TEAM_FAILURE = 'CREATE_NEW_TEAM_FAILURE';




