export const LOAD_USER = 'LOAD_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SAVE_RECEIPT_REQUEST = 'SAVE_RECEIPT_REQUEST';
export const SAVE_RECEIPT_SUCCESS = 'SAVE_RECEIPT_SUCCESS';
export const SAVE_RECEIPT_FAILURE = 'SAVE_RECEIPT_FAILURE';